kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: primary-postgres
spec:
  storageClassName: csi-cinder-high-speed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi