# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - aspect/depencencies ğŸ“¦ï¸
      - aspect/dex ğŸ¤–
      - domain/obvious ğŸŸ©
      - state/triage ğŸš¦
    schedule:
      day: sunday
      interval: monthly
  - package-ecosystem: gomod
    directory: /
    labels:
      - aspect/depencencies ğŸ“¦ï¸
      - aspect/backend ğŸ’»
      - domain/obvious ğŸŸ©
      - state/triage ğŸš¦
    schedule:
      day: sunday
      interval: monthly
  - package-ecosystem: npm
    directory: /web/ui
    labels:
      - aspect/depencencies ğŸ“¦ï¸
      - aspect/interface ğŸ•¹
      - domain/obvious ğŸŸ©
      - state/triage ğŸš¦
    schedule:
      interval: monthly
