name: Issues - Stolen ğŸ¦´
on:
  schedule:
  - cron: "42 8,23 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v6
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 12
          days-before-pr-stale: -1
          days-before-pr-close: -1
          
          stale-issue-label: "state/slote ğŸ¦´,stale/stale ğŸ¦´"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          
          close-issue-label: "state/slote ğŸ¦´,stale/dead ğŸ’€"
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."

          exempt-issue-labels: "state/confirmed ğŸ’œ,slate/lock ğŸ”’"
          exempt-pr-labels: "state/confirmed ğŸ’œ,slate/lock ğŸ”’"
          exempt-all-milestones: true
          exempt-assignees: "42Atomys"

          remove-stale-when-updated: true
          labels-to-add-when-unstale: "stale/unstale ğŸ–"
          labels-to-remove-when-unstale: "stale/stale ğŸ¦´,stale/dead ğŸ’€,state/slote ğŸ¦´"

          enable-statistics: true
